### ISSUE TITLE
edit homepath.conf cause error

### ISSUE THREAD

**Issue by linuxlionking** [LittleSimpleWallpaperChanger/lswc#1]
I edit homepath.conf to change the path of picture , lswc can not run with these error 

username@username-E460:~/.local/scripts/lswc$ ./lswc
Traceback (most recent call last):
  File "./lswc", line 83, in <module>
    browse_button()
  File "./lswc", line 34, in browse_button
    cycle_fe()
  File "./lswc", line 75, in cycle_fe
    filename=random.choice(os.listdir(conf_path))
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/usr/share/backgrounds\n'

I thinik  the "\n" in the path should be deleted

**Comment by LittleSimpleWallpaperChanger** [comment]
Thanks for reporting,

I think you are right. delete the '\n'
