### ISSUE TITLE
Change screensaver image too with the desktop image

### ISSUE THREAD

**Issue by lallenfrancisl** [LittleSimpleWallpaperChanger/lswc#2]
I think the screen saver image should also be changed with the wallpaper.

And if you are okay with this, I would like to work on it too, I know it's small but it could become my first pull request to opensource.

**Comment by LittleSimpleWallpaperChanger** [comment]
hi  l**allenfrancisl** Thanks for your thoughts,
As the name suggests, its a wallpaper-changer **:-)**

if you clean your desktop from icons, and let the dock autohide, you already have an ongoing screensaver. As i did with the addition of radiotray made one of my older laptop-computers a digital photoframe while playing some webradiochannels.

anyhow.. feel free to experiment with the LSWC code. I wish you lots of happiness.

Kind regards,

Ronald

**Comment by lallenfrancisl** [comment]
@LittleSimpleWallpaperChanger  No what I meant by screensaver is the lockscreen. The screen which comes when screen timeout happens.

**Comment by LittleSimpleWallpaperChanger** [comment]
I dare you to write a lockscreen changer.  

Lswc is a wallpaper changer. As small as can be, with the notion of low use of resources.

I understand your idea, and give you a headsup with sending you this link.
https://vitux.com/how-to-change-login-lock-screen-background-in-ubuntu/

good luck!
