### ISSUE TITLE
Dark Themes

### ISSUE THREAD

**Issue by ArduinoShop** [LittleSimpleWallpaperChanger/lswc#3]
Just a comment for Ubuntu 22.04

I just installed the "new" version of lswc on my recent 22.04 updated Ubuntu..  I have used the previous version successfully for a long time.

No joy out of the box....   after some digging I found the problem - Like many people that spend a lot of time on a computer I use "dark" themes to reduce eye fatigue..

It looks like 22.04 uses 2 options to set the "desktop.background":   "picture-uri"  and  "picture-uri-dark"...

I changed your script to:
    os.system("gsettings set org.gnome.desktop.background picture-uri-dark" + full_path)

.....and all joy was had  ... 

this, of course, is a brute force for my situation - you might want to warn...  or just set both...

....   just saying ....

**Comment by LittleSimpleWallpaperChanger** [comment]
Thank you for your comment. I found out right after version 22.04 came out and i wrote about it on the front page in the readme section. There you could find the same solution you probably had to find out on your own. Anyway, i thank you for your dedication to the program, and the likings you talked about. The plan i made to have to place the 'dark mode' file also in the available files to download, is there.. but i have to find a moment for it.  its coming..  soon ;-}

Kind regards..

**Comment by LittleSimpleWallpaperChanger** [comment]
I added the program for Light and Dark theme as a new download.
